{{cpp/title|generic_category}}
{{cpp/error/navbar}}
{{ddcl|header=system_error|since=c++11|
const std::error_category&amp; generic_category() noexcept;
}}

获取到代表通用错误的静态错误类别对象的引用。要求该对象覆写虚函数 {{c|error_category::name()}} 已返回指向字符串 {{c|"generic"}} 的指针。它用于鉴别对应 POSIX {{lc|errno}} 码的错误条件。

===参数===
（无）

===返回值===
到派生于 {{lc|std::error_category}} 的未指定运行时类型的静态对象的引用。

===示例===
{{example
|code=
#include &lt;cerrno&gt;
#include &lt;iostream&gt;
#include &lt;string&gt;
#include &lt;system_error&gt;

int main()
{
    std::error_condition econd = std::generic_category().default_error_condition(EDOM);
    std::cout &lt;&lt; "Category: " &lt;&lt; econd.category().name() &lt;&lt; '\n'
              &lt;&lt; "Value: " &lt;&lt; econd.value() &lt;&lt; '\n'
              &lt;&lt; "Message: " &lt;&lt; econd.message() &lt;&lt; '\n';
}
|output=
Category: generic
Value: 33
Message: Numerical argument out of domain
}}

===参阅===
{{dsc begin}}
{{dsc inc|cpp/error/dsc system_category}}
{{dsc inc|cpp/error/dsc errc}}
{{dsc end}}

{{langlinks|de|en|es|fr|it|ja|pt|ru}}