{{cpp/title|make_exception_ptr}}
{{cpp/error/navbar}}
{{ddcla|header=exception|since=c++11|constexpr=c++26|
template&lt; class E &gt;
std::exception_ptr make_exception_ptr( E e ) noexcept;
}}

创建一个保有到 {{c|e}} 副本的引用的 {{lc|std::exception_ptr}}。这如同执行下列代码：

{{source|
try
{
    throw e;
}
catch(...)
{
    return std::current_exception();
}
}}

===参数===
{{par begin}}
{{par|e|要创建对其副本的引用的异常对象}}
{{par end}}

===返回值===
{{lc|std::exception_ptr}} 实例，它保有到 {{tt|e}} 副本，或到 {{lc|std::bad_alloc}} 实例，或到 {{lc|std::bad_exception}} 实例的引用（参阅 {{lc|std::current_exception}}）。

===注解===
参数按值传递，并受切片影响。

{{ftm begin}}
{{ftm|__cpp_lib_constexpr_exceptions|value=202411L|std=C++26|{{c/core|constexpr}} 的异常类型}}
{{ftm end}}

===示例===
{{example}}

===参阅===
{{dsc begin}}
{{dsc inc|cpp/error/dsc current_exception}}
{{dsc end}}

{{langlinks|de|en|es|fr|it|ja|pt|ru}}