{{cpp/title|nested_exception}}
{{cpp/error/navbar}}
{{ddcl|header=exception|since=c++11|1=
class nested_exception;
}}

{{tt|std::nested_exception}} 是一个多态混入类，可以捕获并存储当前异常，令任意类型的异常彼此间内嵌变得可行。

{{rrev|since=c++26|{{tt|std::nested_exception}} 的成员函数均为 {{c/core|constexpr}}。}}

===成员函数===
{{dsc begin}}
{{dsc mem ctor|cpp/error/nested_exception/nested_exception|构造 nested_exception}}
{{dsc mem vdtor|cpp/error/nested_exception/~nested_exception|析构 nested exception}}
{{dsc mem fun|cpp/error/nested_exception/operator{{=}}|替换 nested_exception 的内容}}
{{dsc mem fun|cpp/error/nested_exception/rethrow_nested|抛出存储的异常}}
{{dsc mem fun|cpp/error/nested_exception/nested_ptr|获得指向存储的异常的指针}}
{{dsc end}}

===非成员函数===
{{dsc begin}}
{{dsc inc|cpp/error/dsc throw_with_nested}}
{{dsc inc|cpp/error/dsc rethrow_if_nested}}
{{dsc end}}

===注解===
{{ftm begin}}
{{ftm|__cpp_lib_constexpr_exceptions|value=202411L|std=C++26|{{c/core|constexpr}} 的异常类型}}
{{ftm end}}

===示例===
{{include|cpp/error/example_nested_exception}}

===参阅===
{{dsc begin}}
{{dsc inc|cpp/error/dsc exception_ptr}}
{{dsc inc|cpp/error/dsc throw_with_nested}}
{{dsc inc|cpp/error/dsc rethrow_if_nested}}
{{dsc end}}

{{langlinks|de|en|es|fr|it|ja|pt|ru}}