{{cpp/title|domain_error}}
{{cpp/error/navbar}}
{{ddcl|header=stdexcept|
class domain_error;
}}

Defines a type of object to be thrown as exception. It may be used by the implementation to report domain errors, that is, situations where the inputs are outside of the domain on which an operation is defined.

The standard library components do not throw this exception (mathematical functions report domain errors as specified in {{lc|math_errhandling}}). Third-party libraries, however, use this. For example, [https://www.boost.org/doc/libs/1_55_0/libs/math/doc/html/math_toolkit/error_handling.html boost.math] throws {{tt|std::domain_error}} if {{tt|boost::math::policies::throw_on_error}} is enabled (the default setting).

{{inheritance diagram/std-domain_error}}

===Member functions===
{{cpp/error/exception/member of derived with message|domain_error}}

{{inherited|[[cpp/error/logic_error|{{small|std::}}logic_error]]|}}

{{cpp/error/exception/inherit}}

===Defect reports===
{{dr list begin}}
{{dr list item|wg=lwg|dr=254|std=C++98|before=the constructor accepting {{c|const char*}} was missing|after=added}}
{{dr list item|wg=lwg|dr=471|std=C++98|before=the explanatory strings of {{tt|std::domain_error}}'s&lt;br&gt;copies were implementation-defined|after=they are the same as that of the&lt;br&gt;original {{tt|std::domain_error}} object}}
{{dr list end}}

{{langlinks|de|es|fr|it|ja|pt|ru|zh}}