{{cpp/error/nested_exception/title|rethrow_nested}}
{{cpp/error/nested_exception/navbar}}
{{ddcla|since=c++11|constexpr=c++26|1=
[[noreturn]] void rethrow_nested() const;
}}

Rethrows the stored exception. If there is no stored exceptions (i.e. {{lc|nested_ptr()}} returns null pointer), then {{lc|std::terminate}} is called.

===Parameters===
(none)

===Return value===
(none)

{{langlinks|ja|ru|zh}}