{{cpp/title|{{small|generator&lt;Ref,V,Allocator&gt;::promise_type::}}unhandled_exception}}
{{cpp/coroutine/generator/navbar}}
{{ddcl|since=c++23|
void unhandled_exception();
}}

Let {{c|x}} be some {{lt|cpp/coroutine/generator}} object.

If a [[cpp/coroutine/generator#Data members|handle]] referring to the coroutine whose {{rlp|/|promise object}} is {{c|*this}} is at the top of {{box|{{c/core|*}}{{lsi|cpp/coroutine/generator#active_}}}} of {{c|x}}:
* If the handle referring to the coroutine whose promise object is {{c|*this}} is the only element of {{c|*x.active_}}, equivalent to {{c|throw;}}.
* Otherwise, assigns {{lc|std::current_exception()}} to {{lsi|cpp/coroutine/generator/promise_type#except_}}.

Otherwise, the behavior is undefined.

===Exceptions===
May throw.

{{langlinks|de|es|fr|it|ja|pt|ru|zh}}